# Generated by Django 5.0.7 on 2024-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagePath',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
