# Generated by Django 5.0.7 on 2024-08-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_imagepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imagePath',
            new_name='image_path',
        ),
    ]
